controller:
  #kind: DaemonSet
  replicaCount: 6
  service:
    #externalTrafficPolicy: Local
    type: NodePort
    nodePorts: 
     http: 31709
  tolerations:
    - key: "ingress"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
  nodeSelector:
    ingress: "true"

